version: '3.1'

services:
  bookstore:
    build:
      context: packages/bookstore
    container_name: bookstore
    ports:
      - "3000:3000"
    depends_on:
      - inventory

  inventory:
    build:
      context: packages/inventory-api
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    hostname: "localhost"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bookstore

  zap:
    build:
      context: ./packages/bookstore/zap
      dockerfile: Zap_Dockerfile
    container_name: zap
    user: zap
    ports:
      - "8080:8080"
    volumes:
      - ./packages/bookstore/zap/configs:/packages/bookstore/zap/configs
    restart: always
    depends_on:
      - bookstore
      - inventory
