version: '3.1'

services:
#  bookstore:
#    build:
#      context: packages/bookstore
#    ports:
#      - "3000:3000"
#    depends_on:
#      - inventory
  inventory:
    build:
      context: packages/inventory-api
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bookstore
