name: Bookstore Workflow
on: [ push ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm i
          npx lerna bootstrap

      - name: Run Unit Test
        run: npx lerna run test

      - name: Code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docker images
        run: | 
          docker-compose up -d
          npx lerna run db:init
        

      - name: Install cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          runTests: false
          wait-on: 'http://localhost:3000'
          working-directory: packages/bookstore

      - name: Cypress run through Zap proxy
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          headless: true
          working-directory: packages/bookstore
        env:
          HTTP_PROXY: http://localhost:8080
          HTTPS_PROXY: http://localhost:8080
        config: baseUrl=http://bookstore:3000


      - name: Zap scan
        run: sh ./packages/bookstore/zap/scripts/zapScan.sh -as local

